### ISSUE TITLE
Delete DigitalRepresentation

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/wot-ontology#20]
Should the DigitalRepresentation class be deleted?

The description says "A digital representation encapsulates a physical object accessible via Web services"

It is marked as unstable so far.

**Comment by rgcmme** [comment]
I think so, that definition is defining a Thing representation (ThingDescription). 
Besides, in the current implementation both classes contain the same definition, so they are the same.

**Comment by mariapoveda** [comment]
Deleted.
