### ISSUE TITLE
defaultValue for properties

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/wot-ontology#21]
@fserena is the defaultValue attribute in the wot:Property class (in wot ontology) a VICINITY or Agora requirement?

**Comment by mariapoveda** [comment]
@AndreaCimminoArriaga is this issue still important?

**Comment by AndreaCimminoArriaga** [comment]
Answering your question first, I do not think so. This matter is not relevant anymore.

**Comment by mariapoveda** [comment]
Won't fix.
