### ISSUE TITLE
Erroneous domain definitions

### ISSUE THREAD

**Issue by vcharpenay** [mariapoveda/wot-ontology#38]
Some domain axioms seem erroneous:

- `:providesInteractionPattern rdfs:domain :InteractionPattern`. I suppose you mean `rdfs:range`?
- `:name rdfs:domain :Thing` leads to the fact that all interaction patterns are also things, which is unwanted, I guess.

In general, are domain/range axioms supposed to remain in the ontology or will they eventually be removed?

**Comment by mariapoveda** [comment]
Thanks for the comments I'll update the ontology.


 I'd rather to keep them in the ontology.

**Comment by mariapoveda** [comment]
Closed in https://github.com/mariapoveda/wot-ontology/commit/ea30b5a64957b2b25302a6c54fd8831296169e36
