### ISSUE TITLE
WoT1 terminology doubt

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/wot-ontology#4]
WoT1 "What is a thing in the web thing context?"

Considering that the description refers to physical and virtual entities (The abstract concept of a physical entity that can either be a real-world artifact, such as a device, or a virtual entity that represents physicality, such as a room or group of devices) could the concept be named "Entity"? Just to avoid confusion with owl:Thing

@fserena what do you think?

**Comment by fserena** [comment]
I think "Entity" fits that definition, even though it might be also confusing to use such term instead of Thing, which in this context (IoT) is the main one. Anyway, I don't mind to use any of them.

**Comment by mariapoveda** [comment]
Finally we use Thing to be in line with the IG terminology
