### ISSUE TITLE
add a queueable attribute to action element

### ISSUE THREAD

**Issue by sulfo4229** [mariapoveda/wot-ontology#43]
Some action implementations could benefit from the ability to queue incoming requests for action execution. However, not all of them. Therefore we propose to have a new attribute, 'queueable', in action description. The attribute would be a simple true or false, so the system can decide, whether or not there can be a queue of requests waiting to execute given action.

**Comment by mariapoveda** [comment]
Fixed. Added property and axiom in Action class
